### ISSUE TITLE
Retry image downloads if they fail

### ISSUE THREAD

**Issue by mikkeldenker** [Cuely/Cuely#13]
Retry all types of image downloads (sidebar, primary image, favicon etc.). Use exponential backoff with a limit.

**Comment by theuserbl** [comment]
Which old version of Struct is used for https://stract.com ?
Before the search resualts is no favicon included. But since Septeber 2022 it is added to GitHub? 🤔

**Comment by mikkeldenker** [comment]
The favicons were removed a while back as they weren't implemented in a very scalable way. I plan to re-implement them again some time in the future, but right now the main focus is on improving the index
